// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtcK2MaU8a4V5eDG6KreXqVSBSjPwfkzY',
    appId: '1:207440694897:web:a8d7e830bc0cfdd97fd5d0',
    messagingSenderId: '207440694897',
    projectId: 'gastrip-1b263',
    authDomain: 'gastrip-1b263.firebaseapp.com',
    storageBucket: 'gastrip-1b263.appspot.com',
    measurementId: 'G-Z4CWVH7R1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9lEsaUYXvWoWkXLe5FV5RD-NVBc3tUjM',
    appId: '1:207440694897:android:6e747783b055ac1a7fd5d0',
    messagingSenderId: '207440694897',
    projectId: 'gastrip-1b263',
    storageBucket: 'gastrip-1b263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYxE1eacohHNLoUGi0T5RL5GRuFmofick',
    appId: '1:207440694897:ios:5d6953f8667ce0037fd5d0',
    messagingSenderId: '207440694897',
    projectId: 'gastrip-1b263',
    storageBucket: 'gastrip-1b263.appspot.com',
    iosBundleId: 'com.example.projetoMoveis2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxE1eacohHNLoUGi0T5RL5GRuFmofick',
    appId: '1:207440694897:ios:5d6953f8667ce0037fd5d0',
    messagingSenderId: '207440694897',
    projectId: 'gastrip-1b263',
    storageBucket: 'gastrip-1b263.appspot.com',
    iosBundleId: 'com.example.projetoMoveis2024',
  );
}
